# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Stamp URL
      run: |
        echo '#!/usr/bin/env bash' > github-url.sh
        echo "export GITHUB_WORKFLOW_URL='${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}'" >> github-url.sh
    - name: Run minimizer
      uses: coq-community/docker-coq-action@v1.4.1
      with:
        #custom_image: 'registry.gitlab.com/coq/coq:CACHEKEY'
        #coq_version: 'latest'
        #ocaml_version: 'default'
        custom_script: ./timeout-run.sh
      timeout-minutes: 330 # Each job in a workflow can run for up to 6 hours of execution time, we want to make sure there's time to upload the files

    - run: cat bug.v
      if: always()

    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: bug.v
        path: bug.v
      if: always()

    - name: Upload output log
      uses: actions/upload-artifact@v3
      with:
        name: bug.log
        path: bug.log
      if: always()

    - name: Upload verbose output log
      uses: actions/upload-artifact@v3
      with:
        name: bug.verbose.log
        path: bug.verbose.log
      if: always()

    - name: Upload build log
      uses: actions/upload-artifact@v3
      with:
        name: build.log
        path: build.log
      if: always()

    - name: Upload temp file
      uses: actions/upload-artifact@v3
      with:
        name: tmp.v
        path: tmp.v
      if: always()

    - name: Upload metadata file
      uses: actions/upload-artifact@v3
      with:
        name: metadata
        path: metadata
      if: always()

    - name: Make a single build artifact
      run: |
        rm -rf /tmp/artifact.tar.gz
        echo '::group::tar -czvf /tmp/artifact.tar.gz .'
        sudo chown -R $(id -u):$(id -g) . # most important for ./tmp/
        sudo tar -czvf /tmp/artifact.tar.gz .
        echo '::endgroup::'
        sudo chown $(id -u):$(id -g) /tmp/artifact.tar.gz
        du -sh /tmp/artifact.tar.gz
      if: always()

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: /tmp/artifact.tar.gz
      if: always()
